trigger: none

pool: My Agent

stages:
- stage: installed
  displayName: Install
  jobs:
  - job: 
    displayName: Terraform Install
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: tfsec@1
      inputs:
        version: 'v1.26.0'
        dir: 'https://github.com/kishorr4/Assignment_Repo'