trigger: none

pool: My Agent

stages:
- stage: installed
  displayName: Install
  jobs:
  - job: 
    displayName: Terraform Install
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'ConnectionForInfra'
        backendAzureRmOverrideSubscriptionID: 'ba0b20ad-8e5c-46a3-935a-06c38c9ce67e'
        backendAzureRmResourceGroupName: 'tolu-rg'
        backendAzureRmStorageAccountName: 'tolustorage1234'
        backendAzureRmContainerName: 'tolucon'
        backendAzureRmKey: 'dev.terraform.tfstate'